apiVersion: v1
kind: Secret
metadata:
  name: pg-airman-mcp-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: pg-airman-mcp
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  DATABASE_URI: "postgresql://{{ .Values.postgres.user | urlquery }}:{{ .Values.postgres.password | urlquery }}@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}"
