kind: Secret
apiVersion: v1
metadata:
  name: vector-database
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: pgvector
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
data:
  # PostgreSQL credentials - used by both the database and pgAdmin
  DATABASE_USER: {{ .Values.postgres.userId | b64enc | quote}}
  DATABASE_PASSWORD: {{ .Values.postgres.password | b64enc | quote }}
  DATABASE_NAME: {{ .Values.postgres.databaseName | b64enc | quote }}
type: Opaque
