apiVersion: v1
kind: Service
metadata:
  name: pgvector-postgres-service
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: pgvector
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app.kubernetes.io/name: pgvector
  ports:
    - protocol: TCP
      port: 5432
      targetPort: postgresql
      name: postgresql
  clusterIP: None
  type: ClusterIP
